"""describe_changes

Revision ID: 4dd212b06940
Revises: eda4ae9c95c3
Create Date: 2026-06-11 08:27:12.253340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4dd212b06940'
down_revision: Union[str, None] = 'eda4ae9c95c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
