"""initial

Revision ID: eda4ae9c95c3
Revises: 
Create Date: 2026-06-11 01:47:30.971893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eda4ae9c95c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_guid'), 'users', ['guid'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('projects',
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', 'completed', name='projectstatus'), nullable=False),
    sa.Column('owner_guid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_guid'], ['users.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_projects_guid'), 'projects', ['guid'], unique=False)
    op.create_index(op.f('ix_projects_owner_guid'), 'projects', ['owner_guid'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('user_guid', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_guid'], ['users.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('analogs',
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('patent_notes', sa.Text(), nullable=True),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('project_guid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.guid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_guid'], ['projects.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_analogs_guid'), 'analogs', ['guid'], unique=False)
    op.create_index(op.f('ix_analogs_project_guid'), 'analogs', ['project_guid'], unique=False)
    op.create_table('annotations',
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('info_sources', sa.Text(), nullable=True),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('project_guid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.guid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_guid'], ['projects.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_annotations_guid'), 'annotations', ['guid'], unique=False)
    op.create_index(op.f('ix_annotations_project_guid'), 'annotations', ['project_guid'], unique=False)
    op.create_table('architecture',
    sa.Column('diagram_type', sa.Enum('plantuml', 'mermaid', 'text', name='diagramtype'), nullable=True),
    sa.Column('diagram_content', sa.Text(), nullable=True),
    sa.Column('layer', sa.String(length=100), nullable=True),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('project_guid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.guid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_guid'], ['projects.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_architecture_guid'), 'architecture', ['guid'], unique=False)
    op.create_index(op.f('ix_architecture_project_guid'), 'architecture', ['project_guid'], unique=False)
    op.create_table('business_goals',
    sa.Column('metric', sa.String(length=255), nullable=True),
    sa.Column('deadline', sa.String(length=100), nullable=True),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('project_guid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.guid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_guid'], ['projects.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_business_goals_guid'), 'business_goals', ['guid'], unique=False)
    op.create_index(op.f('ix_business_goals_project_guid'), 'business_goals', ['project_guid'], unique=False)
    op.create_table('change_records',
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('change_type', sa.Enum('added', 'modified', 'removed', name='changetype'), nullable=True),
    sa.Column('section_ref', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('project_guid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.guid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_guid'], ['projects.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_change_records_guid'), 'change_records', ['guid'], unique=False)
    op.create_index(op.f('ix_change_records_project_guid'), 'change_records', ['project_guid'], unique=False)
    op.create_table('constraints',
    sa.Column('constraint_type', sa.Enum('technical', 'business', 'legal', 'resource', name='constrainttype'), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('project_guid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.guid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_guid'], ['projects.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_constraints_guid'), 'constraints', ['guid'], unique=False)
    op.create_index(op.f('ix_constraints_project_guid'), 'constraints', ['project_guid'], unique=False)
    op.create_table('data_dictionary',
    sa.Column('entity', sa.String(length=255), nullable=True),
    sa.Column('attributes', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(length=100), nullable=True),
    sa.Column('constraints', sa.Text(), nullable=True),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('project_guid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.guid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_guid'], ['projects.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_data_dictionary_guid'), 'data_dictionary', ['guid'], unique=False)
    op.create_index(op.f('ix_data_dictionary_project_guid'), 'data_dictionary', ['project_guid'], unique=False)
    op.create_table('data_flows',
    sa.Column('diagram_type', sa.Enum('plantuml', 'mermaid', 'text', name='diagramtype'), nullable=True),
    sa.Column('diagram_content', sa.Text(), nullable=True),
    sa.Column('actors', sa.Text(), nullable=True),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('project_guid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.guid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_guid'], ['projects.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_data_flows_guid'), 'data_flows', ['guid'], unique=False)
    op.create_index(op.f('ix_data_flows_project_guid'), 'data_flows', ['project_guid'], unique=False)
    op.create_table('draft_tz',
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('project_guid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.guid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_guid'], ['projects.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_draft_tz_guid'), 'draft_tz', ['guid'], unique=False)
    op.create_index(op.f('ix_draft_tz_project_guid'), 'draft_tz', ['project_guid'], unique=False)
    op.create_table('final_tz',
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('project_guid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.guid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_guid'], ['projects.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_final_tz_guid'), 'final_tz', ['guid'], unique=False)
    op.create_index(op.f('ix_final_tz_project_guid'), 'final_tz', ['project_guid'], unique=False)
    op.create_table('glossary_terms',
    sa.Column('term', sa.String(length=255), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('project_guid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.guid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_guid'], ['projects.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_glossary_terms_guid'), 'glossary_terms', ['guid'], unique=False)
    op.create_index(op.f('ix_glossary_terms_project_guid'), 'glossary_terms', ['project_guid'], unique=False)
    op.create_table('non_functional_requirements',
    sa.Column('category', sa.Enum('performance', 'security', 'reliability', 'scalability', 'usability', 'maintainability', 'other', name='nfrcategory'), nullable=True),
    sa.Column('metric', sa.String(length=255), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('project_guid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.guid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_guid'], ['projects.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_non_functional_requirements_guid'), 'non_functional_requirements', ['guid'], unique=False)
    op.create_index(op.f('ix_non_functional_requirements_project_guid'), 'non_functional_requirements', ['project_guid'], unique=False)
    op.create_table('project_files',
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('project_guid', sa.String(length=36), nullable=False),
    sa.Column('section_type', sa.String(length=100), nullable=True),
    sa.Column('section_guid', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('filepath', sa.String(length=1000), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=200), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_guid'], ['projects.guid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.guid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_project_files_guid'), 'project_files', ['guid'], unique=False)
    op.create_index(op.f('ix_project_files_project_guid'), 'project_files', ['project_guid'], unique=False)
    op.create_table('project_users',
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('project_guid', sa.String(length=36), nullable=False),
    sa.Column('user_guid', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('owner', 'editor', 'viewer', name='projectuserrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_guid'], ['projects.guid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_guid'], ['users.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_project_users_project_guid'), 'project_users', ['project_guid'], unique=False)
    op.create_table('requirements',
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='requirementpriority'), nullable=True),
    sa.Column('status', sa.Enum('new', 'accepted', 'rejected', 'deferred', name='requirementstatus'), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('project_guid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.guid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_guid'], ['projects.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_requirements_guid'), 'requirements', ['guid'], unique=False)
    op.create_index(op.f('ix_requirements_project_guid'), 'requirements', ['project_guid'], unique=False)
    op.create_table('system_requirements',
    sa.Column('component', sa.String(length=255), nullable=True),
    sa.Column('specification', sa.Text(), nullable=True),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('project_guid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.guid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_guid'], ['projects.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_system_requirements_guid'), 'system_requirements', ['guid'], unique=False)
    op.create_index(op.f('ix_system_requirements_project_guid'), 'system_requirements', ['project_guid'], unique=False)
    op.create_table('use_cases',
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('preconditions', sa.Text(), nullable=True),
    sa.Column('main_flow', sa.Text(), nullable=True),
    sa.Column('alt_flows', sa.Text(), nullable=True),
    sa.Column('postconditions', sa.Text(), nullable=True),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('project_guid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.guid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_guid'], ['projects.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_use_cases_guid'), 'use_cases', ['guid'], unique=False)
    op.create_index(op.f('ix_use_cases_project_guid'), 'use_cases', ['project_guid'], unique=False)
    op.create_table('user_classes',
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('privileges', sa.Text(), nullable=True),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('project_guid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.guid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_guid'], ['projects.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_user_classes_guid'), 'user_classes', ['guid'], unique=False)
    op.create_index(op.f('ix_user_classes_project_guid'), 'user_classes', ['project_guid'], unique=False)
    op.create_table('user_stories',
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('benefit', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='requirementpriority'), nullable=True),
    sa.Column('status', sa.Enum('todo', 'in_progress', 'done', name='userstorystatus'), nullable=True),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('project_guid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.guid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_guid'], ['projects.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_user_stories_guid'), 'user_stories', ['guid'], unique=False)
    op.create_index(op.f('ix_user_stories_project_guid'), 'user_stories', ['project_guid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_stories_project_guid'), table_name='user_stories')
    op.drop_index(op.f('ix_user_stories_guid'), table_name='user_stories')
    op.drop_table('user_stories')
    op.drop_index(op.f('ix_user_classes_project_guid'), table_name='user_classes')
    op.drop_index(op.f('ix_user_classes_guid'), table_name='user_classes')
    op.drop_table('user_classes')
    op.drop_index(op.f('ix_use_cases_project_guid'), table_name='use_cases')
    op.drop_index(op.f('ix_use_cases_guid'), table_name='use_cases')
    op.drop_table('use_cases')
    op.drop_index(op.f('ix_system_requirements_project_guid'), table_name='system_requirements')
    op.drop_index(op.f('ix_system_requirements_guid'), table_name='system_requirements')
    op.drop_table('system_requirements')
    op.drop_index(op.f('ix_requirements_project_guid'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_guid'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_project_users_project_guid'), table_name='project_users')
    op.drop_table('project_users')
    op.drop_index(op.f('ix_project_files_project_guid'), table_name='project_files')
    op.drop_index(op.f('ix_project_files_guid'), table_name='project_files')
    op.drop_table('project_files')
    op.drop_index(op.f('ix_non_functional_requirements_project_guid'), table_name='non_functional_requirements')
    op.drop_index(op.f('ix_non_functional_requirements_guid'), table_name='non_functional_requirements')
    op.drop_table('non_functional_requirements')
    op.drop_index(op.f('ix_glossary_terms_project_guid'), table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_guid'), table_name='glossary_terms')
    op.drop_table('glossary_terms')
    op.drop_index(op.f('ix_final_tz_project_guid'), table_name='final_tz')
    op.drop_index(op.f('ix_final_tz_guid'), table_name='final_tz')
    op.drop_table('final_tz')
    op.drop_index(op.f('ix_draft_tz_project_guid'), table_name='draft_tz')
    op.drop_index(op.f('ix_draft_tz_guid'), table_name='draft_tz')
    op.drop_table('draft_tz')
    op.drop_index(op.f('ix_data_flows_project_guid'), table_name='data_flows')
    op.drop_index(op.f('ix_data_flows_guid'), table_name='data_flows')
    op.drop_table('data_flows')
    op.drop_index(op.f('ix_data_dictionary_project_guid'), table_name='data_dictionary')
    op.drop_index(op.f('ix_data_dictionary_guid'), table_name='data_dictionary')
    op.drop_table('data_dictionary')
    op.drop_index(op.f('ix_constraints_project_guid'), table_name='constraints')
    op.drop_index(op.f('ix_constraints_guid'), table_name='constraints')
    op.drop_table('constraints')
    op.drop_index(op.f('ix_change_records_project_guid'), table_name='change_records')
    op.drop_index(op.f('ix_change_records_guid'), table_name='change_records')
    op.drop_table('change_records')
    op.drop_index(op.f('ix_business_goals_project_guid'), table_name='business_goals')
    op.drop_index(op.f('ix_business_goals_guid'), table_name='business_goals')
    op.drop_table('business_goals')
    op.drop_index(op.f('ix_architecture_project_guid'), table_name='architecture')
    op.drop_index(op.f('ix_architecture_guid'), table_name='architecture')
    op.drop_table('architecture')
    op.drop_index(op.f('ix_annotations_project_guid'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_guid'), table_name='annotations')
    op.drop_table('annotations')
    op.drop_index(op.f('ix_analogs_project_guid'), table_name='analogs')
    op.drop_index(op.f('ix_analogs_guid'), table_name='analogs')
    op.drop_table('analogs')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_projects_owner_guid'), table_name='projects')
    op.drop_index(op.f('ix_projects_guid'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_guid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
